### ISSUE TITLE
[ REFACTOR ] 사용하지 않는 메소드, 변수 삭제

### ISSUE THREAD

**Issue by nar0ng** [4ragrant/SCENTASY_BE#23]
## 🛠️ Description for refactor features
리팩토링 작업할 사항에 대해 작성해주세요.
사용하지 않는 메소드, 변수를 정리하는 작업을 합니다.

## 📝 Todo-lists
- [x] Response.createError의 String message 매개변수
- [x] 추가정보 저장 api의 url 반환값 삭제하기
- [x] member 엔티티 중복되는 날짜 칼럼 삭제하기
