### ISSUE TITLE
[ FEATURE ] - 향수 생성 관련 기능 구현

### ISSUE THREAD

**Issue by kayeon2** [4ragrant/SCENTASY_BE#35]
## 🛠️ Description for development features
작업할 사항에 대해 작성해주세요.

## 📝 Todo-lists
- [x] 향수 테이블 생성
- [x] 생성된 향수 저장
- [x] 향수 상세 정보 조회
- [ ] 향수 전체 목록 조회
