### ISSUE TITLE
[ FEATURE ] 생성된 향수 레시피 저장 API

### ISSUE THREAD

**Issue by nar0ng** [4ragrant/SCENTASY_BE#57]
## 🛠️ Description for development features
작업할 사항에 대해 작성해주세요.
생성된 향수 레시피를 저장하는 API를 구현합니다.
## 📝 Todo-lists
- [x] spring - flask 통신
- [x] perfume 엔티티에 배열을 담을 칼럼 추가
- [x] 배열 저장
- [x] 배열 저장하여 이름 매핑 후 리스트 저장
