### ISSUE TITLE
[ FEATURE ] - Chat 관련 기능 구현

### ISSUE THREAD

**Issue by nar0ng** [4ragrant/SCENTASY_BE#7]
## 🛠️ Description for development features
작업할 사항에 대해 작성해주세요.

## 📝 Todo-lists
- [x] 챗봇과의 채팅 기능 구현
- [x] 스프링 - 플라스크 통신
- [x] 날짜별 채팅 내역 조회
- [x] 멤버별 날짜 리스트 조회
- [x] 채팅 시 멤버의 추가정보 함께
