### ISSUE TITLE
[ REFACTOR ] 챗봇 및 레시피 관련 기능 개선

### ISSUE THREAD

**Issue by kayeon2** [4ragrant/SCENTASY_BE#75]
## 🛠️ Description for development features
플라스크에서 챗봇 및 레시피 관련 기능을 개선하고 이에 맞춰 코드를 리팩토링할 예정입니다.

## 📝 Todo-lists
- [x] 노트 이름 매핑 방법 변경
- [x] 불필요한 메소드 삭제
- [x] 채팅 시 멤버 닉네임 전달
- [x] 레시피 생성 시 멤버 좋아하는 향, 싫어하는 향 전달
